//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LinearGraph.rc
//
#define IDC_BTN_BROWSE                  3
#define IDI_LOGO                        102
#define IDD_DLG_DATETIME                108
#define IDD_DLG_SELDATA                 109
#define IDD_DLG_GRAPHNAME               110
#define IDR_MENU_MAIN                   116
#define IDR_ACCELERATOR                 117
#define IDD_DLG_LINEAR                  118
#define IDS_ACTION_STOPPED              121
#define IDS_INVALID_ARGS                122
#define IDD_DLG_FORMATSAVE              122
#define IDS_NUMERIC_OVERFLOW            123
#define IDS_SELECT_TARGET_FOLDER        124
#define IDS_SOURCE_NAME                 125
#define IDS_FREQUENCY                   126
#define IDS_TIMESTAMP                   127
#define IDS_DATAPTS                     128
#define IDS_SOURCE_PATH                 129
#define IDS_FOLDER_PATH_EMPTY           130
#define IDS_FREQUENCY_EMPTY             131
#define IDS_COEFFICIENT_EMPTY           132
#define IDS_APP_CAPTION                 133
#define IDS_SOURCE_SELECT_EMPTY         134
#define IDS_ERR_OPEN_FAILED             135
#define IDS_ERR_LOG_FAILED              136
#define IDS_ERR_SAVE_FAILED             137
#define IDS_ACCESS_DENIED               138
#define IDS_IMGFMT_BMP                  139
#define IDS_IMGFMT_PNG                  140
#define IDS_IMGFMT_JPEG                 141
#define IDS_IMGFMT_GIF                  142
#define IDS_IMGFMT_TIFF                 143
#define IDS_SAVE_IMAGE                  144
#define IDS_SAVE_DATA                   145
#define IDS_DATAFMT_BIN                 146
#define IDS_DATAFMT_TEXT                147
#define IDS_DATAFMT_TEXT_WITHTIME       148
#define IDS_APPLICATIOIN_BUSY           149
#define IDS_OPEN_DOCUMENT               150
#define IDS_PREPARE_VIEW                151
#define IDS_TASKMONITOR_CAPTION         152
#define IDS_SAFE_EXIT                   153
#define IDS_EXIT_CONFIRM                154
#define IDS_EXPORT_DATA                 155
#define IDS_ERR_DOC_CHANGED             156
#define IDS_FILE_EXIST                  157
#define IDS_ERR_OSVER_LOW               158
#define IDS_ERR_OUT_OF_MEMORY           159
#define IDS_ERR_GMEM_OVER               160
#define IDS_DATETIMEUNIT                161
#define IDC_BTN_OK                      1002
#define IDC_EDIT_INFO                   1020
#define IDC_BTN_CANCEL                  1022
#define IDC_DTPICKER_DATE               1023
#define IDC_BTN_COMPARE                 1023
#define IDC_DTPICKER_TIME               1024
#define IDC_BTN_ORIGINAL                1024
#define IDC_EDIT_FREQ_MULTI             1025
#define IDC_BTN_PANORAMA                1025
#define IDC_EDIT_FREQ_BASE              1026
#define IDC_LIST_DATA                   1027
#define IDC_EDIT_TIME_MS                1027
#define IDC_EDIT_NAME                   1028
#define IDC_OPT_PARTGRAPH               1030
#define IDC_OPT_WHOLEGRAPH              1031
#define IDC_EDIT_SAVEDIR                1035
#define IDC_CB_FMTLIST                  1036
#define IDC_CB_FONTS                    1037
#define IDC_EDIT_PARAM2                 1041
#define IDC_EDIT_PARAM1                 1042
#define IDC_CHK_REMINDONWRITE           1043
#define ID_FILE_OPENDATA                40001
#define ID_FILE_SAVEDATA                40002
#define ID_FILE_CLOSEDATA               40003
#define ID_FILE_CLOSEALL                40004
#define ID_FILE_EXITAPP                 40005
#define ID_FILE_SAVEIMAGE               40006
#define ID_FILE_SAVEALL_IMAGE           40007
#define ID_FILE_EXPORT_DATA             40008
#define ID_EDIT_RENAME                  40010
#define ID_EDIT_DATETIME                40011
#define ID_VIEW_RULER                   40013
#define ID_VIEW_COORD                   40014
#define ID_VIEW_LEGEND                  40015
#define ID_VIEW_POSLABEL                40016
#define ID_VIEW_RESTORE                 40017
#define ID_VIEW_ZOOM                    40018
#define ID_VIEW_ZOOMIN                  40019
#define ID_VIEW_ZOOMOUT                 40020
#define ID_VIEW_HORZLINE                40021
#define ID_VIEW_FOREGNDCLR              40022
#define ID_VIEW_BKGNDCLR                40023
#define ID_VIEW_CLEARCMP                40024
#define ID_ANALYZE_SYNC                 40025
#define ID_ANALYZE_LINEAR               40026
#define ID_ANALYZE_POWER                40027
#define ID_ANALYZE_DIFF                 40028
#define ID_ANALYZE_COMPARE              40029
#define ID_OPT_TRANSLUCENTSEL           40030
#define ID_OPT_SELECTTRANSFORM          40031
#define ID_HELP_ABOUT                   40032
#define ID_LAYOUT_TAB                   40034
#define ID_LAYOUT_SINGLECOL             40035
#define ID_LAYOUT_DICOL                 40036
#define ID_LAYOUT_TRECOL                40037
#define ID_HELP_HELP                    40038
#define ID_EDIT_RELOAD                  40040
#define ID_40043                        40043
#define ID_VIEW_                        40044
#define ID_VIEW_SHOWTIMEAXIS            40045

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40046
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
