
#ifndef _HEADER_BLOCK_STRUCT_H_
#define _HEADER_BLOCK_STRUCT_H_

//header code definition
#define INDEX_SEED_HEADER_CODE			'V'
#define DICTIONARY_SEED_HEADER_CODE		'A'
#define STATION_SEED_HEADER_CODE		'S'
#define TIMESPAN_SEED_HEADER_CODE		'T'

//blockette code definition
//volume index block code 
#define FILED_VOLUME_IDENTIFIER			005
#define TELEMETRY_VOLUME_IDENTIFIER		008
#define VOLUME_IDENTIFIER				010
#define VOLUME_STATION_INDEX			011
#define VOLUME_TIMESPAN_INDEX			012

//abbreviation dictionary block code 
#define DATA_FORMAT_DICTIONARY			030
#define COMMENT_DESCRIPTION				031
#define CITED_SOURCE_DICTIONARY			032
#define GENERIC_ABBREVIATION			033
#define UNITS_ABBREVIATION				034
#define BEAM_CONFIGURATION				035
#define FIR_DICTIONARY					041
#define RESPONSE_POLYNOMIAL_DICTIONARY	042
#define RESPONSE_POLES_ZEROS_DICTIONARY	043
#define RESPONSE_COEFFICIENT_DICTIONARY	044
#define RESPONSE_LIST_DICTIONARY		045
#define GENERIC_RESPONSE_DICTIONARY		046
#define DECIMATION_DICTIONARY			047
#define CHANNEL_SENSITIVITY_GAIN_DICTIONARY	048
//same as the block 042
// #define RESPONSE_POLYNOMIAL_DICTIONARY	049

//station block code 
#define STATION_IDENTIFIER				050
#define STATION_COMMENT					051
#define CHANNEL_IDENTIFIER				052
#define RESPONSE_POLES_ZEROS			053
#define RESPONSE_COEFFICIENT			054
#define RESPONSE_LIST					055
#define GENERIC_RESPONSE				056
#define DECIMATION						057
#define CHANNEL_SENSITIVITY_GAIN		058
#define CHANNEL_COMMENT					059
#define RESPONSE_REFERENCE				060
#define FIR_RRSPONSE					061
#define RESPONSE_POLYNMIAL				062

//time span code 
#define TIMESPAN_IDENTIFIER				070
#define HYPOCENTER_INFORMATION			071
#define EVENT_PHASES					072
#define TIMESPAN_DATA_START_INDEX		073
#define TIME_SERIAL_INDEX				074


#endif